INSERT INTO USERS(ID, USERNAME, PASSWORD, ROLE) VALUES (100, 'celler@email.com', '$2y$10$vMAUxiwBYq9NL5p67S2bp.4p7m/3VbXZzWD5eDrilfEdz13gy9m3a', 'ROLE_ADMIN');
INSERT INTO USERS(ID, USERNAME, PASSWORD, ROLE) VALUES (101, 'nreis@email.com', '$2y$10$vMAUxiwBYq9NL5p67S2bp.4p7m/3VbXZzWD5eDrilfEdz13gy9m3a', 'ROLE_CLIENT');
INSERT INTO USERS(ID, USERNAME, PASSWORD, ROLE) VALUES (102, 'dviana@email.com', '$2y$10$vMAUxiwBYq9NL5p67S2bp.4p7m/3VbXZzWD5eDrilfEdz13gy9m3a', 'ROLE_CLIENT');

INSERT INTO SPOTS(ID, CODE, STATUS) VALUES (10, 'A-01', 'FREE');
INSERT INTO SPOTS(ID, CODE, STATUS) VALUES (20, 'A-02', 'FREE');
INSERT INTO SPOTS(ID, CODE, STATUS) VALUES (30, 'A-03', 'OCCUPIED');
INSERT INTO SPOTS(ID, CODE, STATUS) VALUES (40, 'A-04', 'FREE');