INSERT INTO USERS(ID, USERNAME, PASSWORD, ROLE) VALUES (100, 'ebechara@email.com', '123456', 'ROLE_ADMIN');
INSERT INTO USERS(ID, USERNAME, PASSWORD, ROLE) VALUES (101, 'sbueno@email.com', '123456', 'ROLE_CLIENT');
INSERT INTO USERS(ID, USERNAME, PASSWORD, ROLE) VALUES (102, 'tspina@email.com', '123456', 'ROLE_CLIENT');