INSERT INTO USERS(ID, PASSWORD, ROLE, USERNAME) VALUES (100, '123456', 'ROLE_ADMIN', 'ebechara@email.com');
INSERT INTO USERS(ID, PASSWORD, ROLE, USERNAME) VALUES (101, '123456', 'ROLE_CLIENT', 'sbueno@email.com');
INSERT INTO USERS(ID, PASSWORD, ROLE, USERNAME) VALUES (102, '123456', 'ROLE_CLIENT', 'tspina@email.com');